### PR TITLE
apt-get clean before apt-get update

### LINKED ISSUE #4: Do git clean before installing
Otherwise, occasionaly we might run into problems as described in this issue: http://serverfault.com/questions/690639/api-get-error-reading-from-server-under-docker

### PR DESCRIPTION
**Pull request by Tonnu**
Resolves #4

### CODE REVIEW

**Comment by flenter** [comment]
lgtm. Does this affect the performance of the step a lot?

**Comment by Tonnu** [comment]
Not sure whether we should merge this in. According to https://github.com/docker-library/buildpack-deps/issues/40#issuecomment it does help somewhat, but doesn't resolve the issue fully and not for everyone.

**Comment by hatchan** [comment]
I think this will kill the cache each time. A better solution would be to do the apt-get install, and if it fails do this `apt-get clean` command and retry the install.

**Comment by Tonnu** [comment]
Closed in favour of #7

**Pull request closed without merging**
